# Generated by Django 4.0.3 on 2022-03-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Flight_name',
            new_name='flight_name',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Flight_name',
            new_name='flight_name',
        ),
    ]
