# Generated by Django 4.0.3 on 2022-05-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_flight_name_book_flight_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='Hi', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phonenum',
            field=models.CharField(default='000', max_length=12),
        ),
    ]
