# Generated by Django 4.0.3 on 2022-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_fullname_user_location_user_phonenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Hi', max_length=30)),
                ('location', models.CharField(default='--', max_length=100)),
                ('phonenum', models.CharField(default='000', max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phonenum',
        ),
    ]
